import type {
  Idea,
  PassionHouseState,
  SocialAccount,
  SocialPlatform,
  UserProfile,
} from "@/lib/passionhouse-types";

const socialUrls: Record<SocialPlatform, string> = {
  X: "https://x.com",
  LinkedIn: "https://linkedin.com",
  GitHub: "https://github.com",
  Instagram: "https://instagram.com",
  Website: "https://example.com",
};

function social(
  platform: SocialPlatform,
  handle: string,
  followers: number,
  growth30d: number,
  trustContribution: number,
): SocialAccount {
  return {
    platform,
    handle,
    url: socialUrls[platform],
    connected: true,
    followers,
    growth30d,
    trustContribution,
  };
}

type UserSeed = Omit<
  UserProfile,
  "email" | "credibilityBreakdown" | "verifications" | "joinedAt" | "socials"
> & { socials: SocialAccount[] };

function user(seed: UserSeed): UserProfile {
  return {
    ...seed,
    email: seed.handle.replace("@", "") + "@passionhouse.demo",
    credibilityBreakdown: {
      external: Math.min(98, seed.credibility + 3),
      execution: Math.min(98, seed.credibility + 1),
      community: Math.max(70, seed.credibility - 3),
      responsiveness: Math.min(98, seed.credibility + 2),
    },
    verifications: ["X identity", seed.identityStyle === "nft" ? "Wallet history" : "Work history", "Community references"],
    joinedAt: "2026-03-14T10:00:00.000Z",
  };
}

const users: UserProfile[] = [
  user({
    id: "u-maya", name: "Maya Chen", handle: "@mayabuilds", title: "Product founder · circular commerce",
    bio: "I turn overlooked operational problems into products people can adopt without changing how they work.",
    location: "London, UK", skills: ["Product strategy", "Marketplaces", "Climate", "Fundraising"],
    avatarTone: "#ff8f70", avatarUrl: "/avatars/maya.svg", identityStyle: "person", credibility: 92,
    projectsBuilt: 4, collaborations: 18, responseRate: 96,
    availableFor: ["Co-founders", "Pilot partners", "Product advisory"],
    socials: [social("X", "@mayabuilds", 28400, 12.4, 18), social("LinkedIn", "maya-chen", 8400, 4.1, 12), social("Website", "mayachen.work", 0, 0, 5)],
  }),
  user({
    id: "u-idris", name: "Idris Bello", handle: "@idrisbuilds", title: "Full-stack engineer · systems builder",
    bio: "Fast product engineering for marketplaces, agent workflows and products with complicated permissions.",
    location: "Berlin, DE", skills: ["TypeScript", "AI agents", "Payments", "Architecture"],
    avatarTone: "#5876ff", avatarUrl: "/avatars/idris.svg", identityStyle: "person", credibility: 88,
    projectsBuilt: 11, collaborations: 23, responseRate: 91,
    availableFor: ["Technical co-founder", "Architecture", "MVP sprints"],
    socials: [social("X", "@idrisbuilds", 17200, 8.7, 17), social("GitHub", "idrisbuilds", 3200, 6.2, 16), social("LinkedIn", "idris-bello", 5100, 2.8, 9)],
  }),
  user({
    id: "u-sofia", name: "Sofia Ramirez", handle: "@sofiar", title: "Growth operator · community products",
    bio: "I validate distribution before scaling the product around it.", location: "Mexico City, MX",
    skills: ["Go-to-market", "Research", "Community", "Partnerships"],
    avatarTone: "#ff679d", avatarUrl: "/avatars/sofia.svg", identityStyle: "person", credibility: 84,
    projectsBuilt: 6, collaborations: 31, responseRate: 88,
    availableFor: ["Go-to-market", "Community design", "Launch partners"],
    socials: [social("X", "@sofiar", 41800, 19.6, 20), social("LinkedIn", "sofia-ramirez", 12600, 7.4, 12), social("Instagram", "@sofia.builds", 22800, 15.1, 10)],
  }),
  user({
    id: "u-theo", name: "Theo Morgan", handle: "@theomakes", title: "AI product designer",
    bio: "Research-led product design for complex tools that need to feel obvious.", location: "New York, US",
    skills: ["Product design", "AI UX", "Prototyping", "Research"],
    avatarTone: "#8f72ff", avatarUrl: "/avatars/theo.svg", identityStyle: "person", credibility: 86,
    projectsBuilt: 9, collaborations: 16, responseRate: 93,
    availableFor: ["Product design", "Design partnerships", "AI UX"],
    socials: [social("X", "@theomakes", 9800, 10.2, 15), social("LinkedIn", "theo-morgan", 6800, 3.9, 11), social("Website", "theomakes.design", 0, 0, 6)],
  }),
  user({
    id: "u-amara", name: "Amara Okafor", handle: "@amaraops", title: "Health operations founder",
    bio: "Building better infrastructure for the people doing frontline care work.", location: "Lagos, NG",
    skills: ["Healthtech", "Operations", "Enterprise sales", "Compliance"],
    avatarTone: "#f2a84a", avatarUrl: "/avatars/amara.svg", identityStyle: "person", credibility: 90,
    projectsBuilt: 5, collaborations: 14, responseRate: 90,
    availableFor: ["Health pilots", "Operations", "Enterprise partnerships"],
    socials: [social("X", "@amaraops", 13700, 7.8, 16), social("LinkedIn", "amara-okafor", 11900, 5.3, 14)],
  }),
  user({
    id: "u-ren", name: "Ren Ito", handle: "@renlabs", title: "Fintech engineer · ex-risk systems",
    bio: "I build trustworthy financial products around the edge cases others ignore.", location: "Singapore",
    skills: ["Fintech", "Risk", "Backend", "Data"],
    avatarTone: "#46a0ff", avatarUrl: "/avatars/ren.svg", identityStyle: "person", credibility: 89,
    projectsBuilt: 13, collaborations: 19, responseRate: 95,
    availableFor: ["Fintech systems", "Risk review", "Backend engineering"],
    socials: [social("X", "@renlabs", 7600, 4.8, 14), social("GitHub", "ren-labs", 4100, 7.7, 18), social("LinkedIn", "ren-ito", 8900, 3.2, 12)],
  }),
  user({
    id: "u-nova", name: "Nova Vale", handle: "@novadoteth", title: "Onchain community designer",
    bio: "DAO contributor turned product operator. Interested in coordination that feels human.", location: "Lisbon, PT",
    skills: ["Web3", "DAOs", "Community", "Token design"],
    avatarTone: "#b35cff", avatarUrl: "/avatars/nova.svg", identityStyle: "nft", credibility: 83,
    projectsBuilt: 7, collaborations: 37, responseRate: 89,
    availableFor: ["Web3 experiments", "Community systems", "Advisory"],
    socials: [social("X", "@novadoteth", 35600, 14.8, 20), social("GitHub", "novavale", 780, 4.2, 8), social("Website", "nova.eth", 0, 0, 8)],
  }),
  user({
    id: "u-aisha", name: "0xAisha", handle: "@0xaisha", title: "DeFi researcher · wallet UX",
    bio: "Researching how normal people understand risk, custody and money movement onchain.", location: "Dubai, UAE",
    skills: ["DeFi", "Research", "Wallet UX", "Security"],
    avatarTone: "#2f93ff", avatarUrl: "/avatars/aisha.svg", identityStyle: "nft", credibility: 87,
    projectsBuilt: 8, collaborations: 21, responseRate: 94,
    availableFor: ["User research", "Protocol design", "Wallet reviews"],
    socials: [social("X", "@0xaisha", 52300, 9.8, 21), social("GitHub", "0xaisha", 2400, 5.5, 13), social("Website", "aisha.xyz", 0, 0, 7)],
  }),
  user({
    id: "u-pixel", name: "Pixel Nomad", handle: "@pixelnomad", title: "NFT artist · creative technologist",
    bio: "Making characters, worlds and tools that let collectors participate in the story.", location: "Internet",
    skills: ["NFT art", "3D", "Generative art", "Creative direction"],
    avatarTone: "#ff5dba", avatarUrl: "/avatars/pixel.svg", identityStyle: "nft", credibility: 81,
    projectsBuilt: 12, collaborations: 29, responseRate: 86,
    availableFor: ["Art collaborations", "NFT launches", "Creative tooling"],
    socials: [social("X", "@pixelnomad", 68400, 11.2, 22), social("Instagram", "@pixel.nomad", 31200, 8.1, 10), social("Website", "pixelnomad.art", 0, 0, 6)],
  }),
  user({
    id: "u-byte", name: "ByteBunny", handle: "@bytebunny", title: "Collector · consumer crypto builder",
    bio: "Collector since 2021. Now building gentler entry points into ownership and digital identity.", location: "Tokyo, JP",
    skills: ["Consumer crypto", "NFTs", "Mobile", "Growth"],
    avatarTone: "#ff7a59", avatarUrl: "/avatars/bytebunny.svg", identityStyle: "nft", credibility: 85,
    projectsBuilt: 6, collaborations: 25, responseRate: 92,
    availableFor: ["Consumer apps", "Collector research", "Beta testing"],
    socials: [social("X", "@bytebunny", 44700, 13.4, 20), social("GitHub", "bytebunny", 1200, 6.9, 10), social("Website", "bytebunny.xyz", 0, 0, 7)],
  }),
];

type IdeaSeed = Pick<Idea, "id" | "creatorId" | "title" | "oneLiner" | "description" | "category" | "stage" | "createdAt"> &
  Partial<Omit<Idea, "id" | "creatorId" | "title" | "oneLiner" | "description" | "category" | "stage" | "createdAt">>;

function idea(seed: IdeaSeed): Idea {
  return {
    signal: 76,
    tags: [seed.category, seed.stage],
    asks: [],
    validation: [],
    likes: 0,
    dislikes: 0,
    interested: 0,
    commentsCount: 0,
    visibility: "public",
    media: [],
    postType: "idea",
    disclosure: "open",
    fullDetails: seed.description,
    accessTiers: {
      context: "Problem framing, audience insight and the opportunity map.",
      build: "Product brief, workflow, validation evidence and build priorities.",
      full: "Complete execution plan, commercial model, risks and private materials.",
    },
    accessPricing: { currency: "USD", context: 0, build: 19, full: 49 },
    ...seed,
  };
}

const ideas: Idea[] = [
  idea({
    id: "idea-loopline", creatorId: "u-maya", title: "Loopline",
    oneLiner: "The returns network small brands can share instead of rebuilding.",
    description: "Independent brands lose margin because every return becomes a separate logistics problem. Loopline pools local inspection, routing and resale into one shared network.",
    fullDetails: "The wedge is a shared condition-grading language for deciding what can be restocked, repaired, bundled or routed to local resale. Twelve brands have signed pilot letters. The first city cluster is dense enough to test whether pooled routes can materially change unit economics.\n\nThe initial product combines a shopper return flow, an operator console and a lightweight brand API. Success means faster refunds, higher recovery value and fewer items sent across borders twice.",
    category: "Climate", stage: "Validated", createdAt: "2026-09-27T10:10:00.000Z", signal: 94,
    tags: ["Commerce", "Logistics", "Circular economy"], asks: ["Full-stack engineer", "Pilot brand introductions"],
    validation: [{ label: "Interviews", value: "84", detail: "Customers + operators" }, { label: "Pilot LOIs", value: "12", detail: "Across 4 categories" }, { label: "Waitlist", value: "462", detail: "+18% this week" }],
    likes: 218, dislikes: 9, interested: 47, commentsCount: 24,
    media: [{ id: "media-loopline-1", kind: "image", name: "Loopline network map", url: "/media/loopline.svg", visibility: "public" }],
  }),
  idea({
    id: "idea-nightjar", creatorId: "u-theo", title: "Nightjar",
    oneLiner: "A private AI workspace for teams that cannot leak the question.",
    description: "A deployable research and drafting copilot for regulated teams, with source-level permissions and a visible decision trail.",
    fullDetails: "Nightjar runs inside a customer-controlled environment. Every answer retains citations, source permissions and a review trail. The first wedge is legal and clinical operations where teams already spend hours reconstructing why a decision was made.\n\nSeven design partners are testing three workflows. Two have converted to paid pilots. The next milestone is a repeatable security package and deployment playbook.",
    category: "AI", stage: "Prototype", createdAt: "2026-09-27T08:30:00.000Z", signal: 91, disclosure: "tiered",
    tags: ["AI", "Privacy", "Enterprise"], asks: ["Security engineer", "Compliance design partner"],
    validation: [{ label: "Partners", value: "7", detail: "2 paid pilots" }, { label: "Weekly tests", value: "126", detail: "Across 31 users" }, { label: "Time saved", value: "6.4h", detail: "Per user / week" }],
    likes: 186, dislikes: 6, interested: 39, commentsCount: 18,
    media: [{ id: "media-nightjar-1", kind: "image", name: "Private workspace concept", url: "/media/nightjar.svg", visibility: "public" }, { id: "media-nightjar-2", kind: "image", name: "Security architecture", url: "/media/private-blueprint.svg", visibility: "private" }],
  }),
  idea({
    id: "idea-civicsignal", creatorId: "u-sofia", title: "CivicSignal",
    oneLiner: "Turn neighborhood friction into a prioritized city action queue.",
    description: "Residents report small local issues through familiar channels. CivicSignal clusters evidence, verifies urgency and gives city teams one actionable operating view.",
    fullDetails: "The product starts with WhatsApp and web intake, then groups duplicate reports by place, time and evidence. City teams see a queue ranked by urgency, recurrence and affected population. Residents receive status updates without downloading another app.\n\nThe pilot improved issue resolution from 17% to 41% across two districts.",
    category: "Civic", stage: "Early traction", createdAt: "2026-09-26T18:20:00.000Z", signal: 88,
    tags: ["Govtech", "Community", "Data"], asks: ["Civic data engineer", "Municipal advisor"],
    validation: [{ label: "Reports", value: "1.8k", detail: "In 2 districts" }, { label: "Resolution", value: "41%", detail: "Up from 17%" }, { label: "City teams", value: "3", detail: "In evaluation" }],
    likes: 143, dislikes: 12, interested: 31, commentsCount: 29,
    media: [{ id: "media-civic-1", kind: "image", name: "CivicSignal operations view", url: "/media/civicsignal.svg", visibility: "public" }],
  }),
  idea({
    id: "idea-atlascare", creatorId: "u-amara", title: "Atlas Care",
    oneLiner: "Shift handovers that frontline care teams can actually trust.",
    description: "A lightweight handover layer that converts voice notes and fragmented updates into role-specific, auditable next actions.",
    fullDetails: "Atlas Care captures the way staff already communicate, then structures it into patients, owners, due times and escalation paths. It does not try to replace the hospital system; it closes the gap between formal records and the real shift.\n\nThree active pilots show 32% fewer missed tasks and 22 minutes saved per handover.",
    category: "Health", stage: "Pilot", createdAt: "2026-09-26T13:15:00.000Z", signal: 90,
    tags: ["Healthtech", "Operations", "Workflow"], asks: ["Clinical product designer", "Mobile engineer"],
    validation: [{ label: "Care teams", value: "9", detail: "3 active pilots" }, { label: "Missed tasks", value: "−32%", detail: "Over 6 weeks" }, { label: "Shift saves", value: "22m", detail: "Median" }],
    likes: 171, dislikes: 4, interested: 36, commentsCount: 16,
    media: [{ id: "media-atlas-1", kind: "image", name: "Atlas Care handover", url: "/media/atlascare.svg", visibility: "public" }],
  }),
  idea({
    id: "idea-kite", creatorId: "u-ren", title: "Kite Ledger",
    oneLiner: "Cash-flow certainty for businesses paid across borders.",
    description: "A treasury assistant that predicts settlement gaps, groups obligations and recommends safer times to convert or move cash.",
    fullDetails: "Kite connects invoice tools, bank accounts and stablecoin wallets into a single cash timeline. It explains upcoming gaps in plain language and lets the owner test scenarios before moving money.\n\nThe beta links $1.2m in monthly flows across 28 teams. The regulated partner and risk logic stay behind instant demo access.",
    category: "Fintech", stage: "Validated", createdAt: "2026-09-25T15:45:00.000Z", signal: 87, disclosure: "tiered",
    tags: ["Fintech", "Treasury", "SMB"], asks: ["Fintech counsel", "Growth co-founder"],
    validation: [{ label: "Volume", value: "$1.2m", detail: "Monthly flows" }, { label: "Beta teams", value: "28", detail: "12 weekly active" }, { label: "Avoided fees", value: "$31k", detail: "Estimated annual" }],
    likes: 132, dislikes: 8, interested: 28, commentsCount: 12,
    media: [{ id: "media-kite-1", kind: "image", name: "Kite treasury timeline", url: "/media/kite.svg", visibility: "public" }],
  }),
  idea({
    id: "idea-proofstack", creatorId: "u-idris", title: "Proofstack",
    oneLiner: "A portable evidence layer for independent specialists.",
    description: "A work passport that turns outcomes, references and verified contributions into reusable proof—without reducing people to a star rating.",
    fullDetails: "Proofstack captures an outcome, who can verify it, the contributor's role and the evidence that can be shared. People carry that proof between marketplaces and clients.\n\nThe first product is a public profile plus a private evidence vault. Four talent networks are interested in a shared verification format.",
    category: "Future of work", stage: "Concept", createdAt: "2026-09-25T11:20:00.000Z", signal: 82,
    tags: ["Identity", "Work", "Reputation"], asks: ["Trust researcher", "Marketplace operator"],
    validation: [{ label: "Interviews", value: "43", detail: "Freelancers + buyers" }, { label: "Tests", value: "19", detail: "74% completion" }, { label: "Partners", value: "4", detail: "Talent networks" }],
    likes: 98, dislikes: 11, interested: 21, commentsCount: 9,
    media: [{ id: "media-proof-1", kind: "image", name: "Portable proof graph", url: "/media/proofstack.svg", visibility: "public" }],
  }),
  idea({
    id: "idea-agentcommons", creatorId: "u-nova", title: "Agent Commons",
    oneLiner: "Reputation and permissions for AI agents that work across communities.",
    description: "A neutral identity layer where autonomous agents earn portable trust through completed work, transparent permissions and human references.",
    fullDetails: "Every agent gets an identity account, a permission manifest and an append-only contribution record. Communities can define their own trust rules without trapping reputation in one platform.\n\nThe MVP focuses on research and community support agents. It will test whether transparent boundaries improve adoption more than another generic agent marketplace.",
    category: "Web3", stage: "Prototype", createdAt: "2026-09-24T17:00:00.000Z", signal: 89,
    tags: ["AI agents", "Onchain identity", "Reputation"], asks: ["Protocol engineer", "Agent community pilots"],
    validation: [{ label: "Agents", value: "32", detail: "Test identities" }, { label: "Communities", value: "5", detail: "Design partners" }, { label: "Tasks", value: "740", detail: "Recorded" }],
    likes: 207, dislikes: 15, interested: 54, commentsCount: 33,
  }),
  idea({
    id: "idea-walletgarden", creatorId: "u-byte", title: "Wallet Garden",
    oneLiner: "A wallet that grows with the user's confidence instead of exposing everything on day one.",
    description: "A mobile wallet with progressive controls: simple saving first, collecting next, DeFi only when the user is ready.",
    fullDetails: "Wallet Garden replaces a settings maze with guided capability levels. Each level explains risk, runs a simulation and lets the user choose a recovery model. Advanced features remain available without dominating the first session.\n\nThirty-two consumer interviews suggest confidence—not interest—is the main barrier to onchain use.",
    category: "Web3", stage: "Concept", createdAt: "2026-09-23T15:10:00.000Z", signal: 85,
    tags: ["Wallet", "Consumer crypto", "Mobile"], asks: ["Mobile engineer", "Wallet infrastructure partner"],
    validation: [{ label: "Interviews", value: "32", detail: "Crypto curious" }, { label: "Prototype", value: "68%", detail: "Task completion" }, { label: "Waitlist", value: "318", detail: "Organic" }],
    likes: 154, dislikes: 7, interested: 42, commentsCount: 19,
  }),
  idea({
    id: "idea-chaincred", creatorId: "u-aisha", title: "ChainCred",
    oneLiner: "Risk-aware credit context built from consented onchain behavior.",
    description: "A user-controlled proof that translates wallet history into understandable financial signals without publishing every transaction.",
    fullDetails: "Users select which accounts and time windows to prove. ChainCred produces narrow claims—income consistency, liquidity buffer or repayment history—using zero-knowledge proofs where appropriate.\n\nThe product is not a universal score. Every claim has a purpose, expiry and visible data boundary.",
    category: "Fintech", stage: "Prototype", createdAt: "2026-09-22T18:40:00.000Z", signal: 86, disclosure: "tiered",
    tags: ["ZK", "Credit", "Privacy"], asks: ["ZK engineer", "Lending design partner"],
    validation: [{ label: "Wallets", value: "1.4k", detail: "Anonymized study" }, { label: "Lenders", value: "6", detail: "Discovery" }, { label: "Claims", value: "4", detail: "Prototype" }],
    likes: 176, dislikes: 18, interested: 45, commentsCount: 26,
    media: [{ id: "media-chaincred-1", kind: "image", name: "Private proof architecture", url: "/media/private-blueprint.svg", visibility: "private" }],
  }),
  idea({
    id: "idea-droproom", creatorId: "u-pixel", title: "DropRoom",
    oneLiner: "A live studio where collectors help shape an NFT collection before mint.",
    description: "Artists share sketches, trait experiments and story branches. Collectors signal what resonates without turning art into a popularity contest.",
    fullDetails: "DropRoom organizes pre-mint participation into limited creative prompts. The artist keeps final control; collectors earn visible contribution credit and optional allowlist status.\n\nThe product makes provenance begin before mint day and gives artists useful demand signals without leaking the final collection.",
    category: "Creator economy", stage: "Prototype", createdAt: "2026-09-21T12:00:00.000Z", signal: 84,
    tags: ["NFT", "Creators", "Community"], asks: ["NFT launch partners", "Realtime engineer"],
    validation: [{ label: "Artists", value: "18", detail: "Interviewed" }, { label: "Collectors", value: "240", detail: "Private test" }, { label: "Sessions", value: "11", detail: "Completed" }],
    likes: 188, dislikes: 13, interested: 49, commentsCount: 31,
  }),
  idea({
    id: "idea-localcompute", creatorId: "u-idris", title: "LocalCompute",
    oneLiner: "Private AI inference that small professional teams can actually operate.",
    description: "A managed local model appliance for clinics, law firms and studios with simple updates, audit logs and predictable cost.",
    fullDetails: "LocalCompute bundles vetted models, a permission layer and remote health monitoring into one appliance. Sensitive inputs stay on site; administrators get a plain-language control panel.\n\nThe pilot target is teams with 20–100 staff that cannot hire an ML platform team.",
    category: "AI", stage: "Concept", createdAt: "2026-09-20T09:40:00.000Z", signal: 81, disclosure: "tiered",
    tags: ["Private AI", "Infrastructure", "Enterprise"], asks: ["Hardware partner", "Security reviewer"],
    validation: [{ label: "Interviews", value: "27", detail: "IT leads" }, { label: "Pilots", value: "3", detail: "Verbal yes" }, { label: "Target", value: "$499", detail: "Monthly" }],
    likes: 119, dislikes: 10, interested: 32, commentsCount: 14,
  }),
  idea({
    id: "idea-skillmint", creatorId: "u-nova", title: "SkillMint",
    oneLiner: "Community-funded learning bounties tied to proof of useful work.",
    description: "Sponsors fund real project briefs. Learners build in public, receive expert review and leave with evidence instead of another certificate.",
    fullDetails: "A sponsor posts a scoped problem and funds a cohort. Learners form small teams, ship weekly artifacts and receive rubric-based feedback. Completion produces a portable proof record with links to the work and reviewer identity.\n\nThe platform takes a service fee on sponsorship, never equity in learner projects.",
    category: "Education", stage: "Validated", createdAt: "2026-09-19T16:25:00.000Z", signal: 83,
    tags: ["Education", "Bounties", "Proof of work"], asks: ["Cohort sponsors", "Expert reviewers"],
    validation: [{ label: "Learners", value: "96", detail: "Pilot cohort" }, { label: "Sponsors", value: "4", detail: "Paid" }, { label: "Completed", value: "71%", detail: "Useful artifacts" }],
    likes: 137, dislikes: 6, interested: 38, commentsCount: 17,
  }),
  idea({
    id: "idea-pulsefund", creatorId: "u-maya", title: "PulseFund",
    oneLiner: "Small, fast project grants decided by evidence of momentum—not polished decks.",
    description: "A microgrant pool for experiments already showing public progress, community pull and a clear next milestone.",
    fullDetails: "Applicants connect their public build trail, define one fundable milestone and show who benefits if it works. Reviewers score momentum, clarity and learning value. Grants range from $2,000 to $20,000.\n\nThe first fund could be operated by PassionHouse with external sponsors co-funding themed rounds.",
    category: "Future of work", stage: "Concept", createdAt: "2026-09-18T11:35:00.000Z", signal: 80,
    tags: ["Funding", "Grants", "Builders"], asks: ["Fund partners", "Grant operators"],
    validation: [{ label: "Builders", value: "118", detail: "Surveyed" }, { label: "Sponsors", value: "3", detail: "Interested" }, { label: "Pilot pool", value: "$50k", detail: "Target" }],
    likes: 126, dislikes: 8, interested: 40, commentsCount: 22,
  }),
  idea({
    id: "idea-archivex", creatorId: "u-pixel", title: "ArchiveX",
    oneLiner: "A living provenance archive for digital art, process and collector stories.",
    description: "Artists and collectors preserve the sketches, decisions, exhibitions and moments that give a digital work cultural context.",
    fullDetails: "ArchiveX lets creators define an official work record while collectors attach signed memories, exhibition photos and display history. The archive stays readable on the web and exports to decentralized storage.\n\nThe goal is not price tracking. It is keeping the human story around digital objects intact.",
    category: "Creator economy", stage: "Concept", createdAt: "2026-09-17T14:10:00.000Z", signal: 79,
    tags: ["NFT", "Art", "Provenance"], asks: ["Museum advisor", "Storage engineer"],
    validation: [{ label: "Artists", value: "22", detail: "Discovery" }, { label: "Works", value: "310", detail: "Test archive" }, { label: "Collectors", value: "74", detail: "Waitlist" }],
    likes: 111, dislikes: 5, interested: 29, commentsCount: 13,
  }),
  idea({
    id: "post-nova-interviews", creatorId: "u-nova", title: "Public user interviews?",
    oneLiner: "What if early user interviews were public by default?",
    description: "What if early user interviews were public by default, with the interviewee's consent? Other founders could learn from the same conversation instead of asking the same ten questions again.",
    category: "Future of work", stage: "Concept", createdAt: "2026-09-27T12:42:00.000Z", postType: "post", signal: 74,
    tags: ["Question", "Research"], likes: 48, dislikes: 3, interested: 15, commentsCount: 18,
  }),
  idea({
    id: "post-pixel-artists", creatorId: "u-pixel", title: "Looking for three NFT artists",
    oneLiner: "Small creative experiment—no giant roadmap.",
    description: "Looking for three NFT artists who want to run a tiny collaborative drop: one shared world, one week, no giant roadmap. Reply with your weirdest unfinished character.",
    category: "Creator economy", stage: "Concept", createdAt: "2026-09-27T11:55:00.000Z", postType: "post", signal: 77,
    tags: ["Collab", "NFT"], asks: ["NFT artists"], likes: 72, dislikes: 2, interested: 26, commentsCount: 21,
  }),
  idea({
    id: "post-aisha-wallets", creatorId: "u-aisha", title: "Wallet UX hot take",
    oneLiner: "Wallets should stop feeling like bank vaults.",
    description: "Hot take: wallets should stop feeling like bank vaults. Most days they should feel like a calm home screen. Security can be strong without making every action feel dangerous.",
    category: "Web3", stage: "Concept", createdAt: "2026-09-27T10:58:00.000Z", postType: "post", signal: 81,
    tags: ["Hot take", "Wallet UX"], likes: 126, dislikes: 14, interested: 33, commentsCount: 37,
  }),
  idea({
    id: "post-amara-clinics", creatorId: "u-amara", title: "Clinic intro needed",
    oneLiner: "Looking for a clinic testing asynchronous shift handovers.",
    description: "Does anyone know a 20–50 person clinic already using WhatsApp or voice notes for shift handovers? I would love one honest conversation—no sales deck.",
    category: "Health", stage: "Pilot", createdAt: "2026-09-26T21:12:00.000Z", postType: "post", signal: 78,
    tags: ["Ask", "Health"], asks: ["Clinic introduction"], likes: 39, dislikes: 1, interested: 19, commentsCount: 12,
  }),
  idea({
    id: "post-idris-agent-schema", creatorId: "u-idris", title: "Tiny agent reputation schema",
    oneLiner: "Built a very small schema for agent work history.",
    description: "I made a tiny schema for agent reputation: task, permission, evidence, reviewer, expiry. It is intentionally boring. Who wants the JSON and wants to break it?",
    category: "AI", stage: "Prototype", createdAt: "2026-09-26T19:44:00.000Z", postType: "post", signal: 80,
    tags: ["Build log", "AI agents"], likes: 93, dislikes: 4, interested: 27, commentsCount: 24,
  }),
  idea({
    id: "post-sofia-pricing", creatorId: "u-sofia", title: "$9 founder research digest?",
    oneLiner: "Would you pay for five useful insights instead of fifty links?",
    description: "Would you pay $9/month for a founder research digest with only five useful observations, each linked to the raw interview clip? Testing whether less content can be the product.",
    category: "Consumer", stage: "Concept", createdAt: "2026-09-26T17:05:00.000Z", postType: "post", signal: 73,
    tags: ["Pricing", "Question"], likes: 56, dislikes: 9, interested: 17, commentsCount: 29,
  }),
];

export const demoState: PassionHouseState = {
  schemaVersion: 3,
  currentUserId: null,
  users,
  ideas,
  comments: [
    { id: "c-1", ideaId: "idea-loopline", userId: "u-idris", body: "The shared inspection language is the wedge. Have you tested how much brands will standardize grading?", createdAt: "2026-09-27T11:20:00.000Z" },
    { id: "c-2", ideaId: "idea-loopline", userId: "u-sofia", body: "The 12 LOIs make this unusually concrete. I can introduce two accessories brands.", createdAt: "2026-09-27T11:45:00.000Z" },
    { id: "c-3", ideaId: "idea-nightjar", userId: "u-maya", body: "The decision trail is more defensible than another generic private chat interface.", createdAt: "2026-09-27T09:30:00.000Z" },
    { id: "c-4", ideaId: "post-aisha-wallets", userId: "u-byte", body: "Yes. Progressive disclosure should apply to risk controls too, not just navigation.", createdAt: "2026-09-27T11:04:00.000Z" },
    { id: "c-5", ideaId: "post-pixel-artists", userId: "u-nova", body: "I have a half-finished cosmic courier character. Sending it your way.", createdAt: "2026-09-27T12:02:00.000Z" },
  ],
  accessRequests: [
    { id: "req-1", ideaId: "idea-loopline", userId: "u-idris", requestedTier: "full", grantedTier: "full", role: "Technical co-founder", note: "I have built multi-party logistics systems and can own the pilot architecture.", status: "approved", createdAt: "2026-09-26T09:15:00.000Z" },
    { id: "req-2", ideaId: "idea-nightjar", userId: "u-maya", requestedTier: "full", grantedTier: "full", role: "Product collaborator", note: "I can help turn pilot learning into a repeatable implementation playbook.", status: "approved", createdAt: "2026-09-23T16:30:00.000Z" },
  ],
  proposals: [
    { id: "prop-1", ideaId: "idea-loopline", fromUserId: "u-idris", toUserId: "u-maya", title: "Pilot architecture sprint", summary: "Turn the pilot map into a working operator console and brand-facing returns flow.", scope: "Architecture, system flow, grading model and a production-ready pilot backlog.", timeline: "4 weeks", budget: "$8,500 fixed", status: "sent", createdAt: "2026-09-26T13:10:00.000Z" },
    { id: "prop-2", ideaId: "idea-nightjar", fromUserId: "u-maya", toUserId: "u-theo", title: "Pilot-to-product operating sprint", summary: "Package the strongest pilot workflows into a repeatable product.", scope: "Workflow prioritization, customer cadence, success scorecard and commercialization plan.", timeline: "6 weeks", budget: "$12,000 fixed", status: "accepted", createdAt: "2026-09-21T15:00:00.000Z" },
  ],
  dealRooms: [
    {
      id: "deal-nightjar", ideaId: "idea-nightjar", participantIds: ["u-maya", "u-theo"], status: "active",
      agreement: { title: "Pilot-to-product operating sprint", budget: "$12,000", timeline: "6 weeks · ends Nov 4", ownership: "Nightjar retains all product IP", platformEquity: "0% — PassionHouse takes no equity" },
      milestones: [{ id: "m-1", title: "Pilot evidence synthesis", due: "Sep 30", amount: "$2,000", status: "complete" }, { id: "m-2", title: "Core workflow specification", due: "Oct 12", amount: "$4,000", status: "active" }, { id: "m-3", title: "Commercial playbook", due: "Nov 4", amount: "$6,000", status: "upcoming" }],
      messages: [{ id: "dm-1", userId: "u-theo", body: "I added the anonymized pilot notes and marked the three workflows with strongest repeat usage.", createdAt: "2026-09-25T15:12:00.000Z" }, { id: "dm-2", userId: "u-maya", body: "Perfect. I will turn those into the prioritization scorecard before our review tomorrow.", createdAt: "2026-09-25T15:18:00.000Z" }],
      documents: [{ id: "doc-1", name: "Signed collaboration terms.pdf", size: "428 KB", uploadedBy: "u-theo" }, { id: "doc-2", name: "Pilot evidence synthesis.pdf", size: "1.8 MB", uploadedBy: "u-maya" }],
    },
  ],
  fundingRequests: [
    { id: "fund-1", ideaId: "idea-agentcommons", userId: "u-nova", audience: "both", amount: "$250,000", summary: "Fund an 18-month protocol and community pilot runway.", useOfFunds: "Protocol engineering, audits and five community pilots.", status: "under-review", createdAt: "2026-09-26T14:00:00.000Z" },
    { id: "fund-2", ideaId: "idea-loopline", userId: "u-maya", audience: "investors", amount: "$180,000", summary: "Launch the first dense city cluster with twelve brands.", useOfFunds: "Operator tooling, local inspection network and pilot logistics.", status: "open", createdAt: "2026-09-25T12:00:00.000Z" },
    { id: "fund-3", ideaId: "idea-droproom", userId: "u-pixel", audience: "passionhouse", amount: "$50,000", summary: "Run ten artist-led collaborative drop rooms.", useOfFunds: "Realtime prototype, creator grants and collector research.", status: "under-review", createdAt: "2026-09-24T10:00:00.000Z" },
    { id: "fund-4", ideaId: "idea-kite", userId: "u-ren", audience: "investors", amount: "$400,000", summary: "Move from beta to regulated production pilots.", useOfFunds: "Compliance, banking integrations and engineering.", status: "open", createdAt: "2026-09-23T10:00:00.000Z" },
    { id: "fund-5", ideaId: "idea-skillmint", userId: "u-nova", audience: "both", amount: "$120,000", summary: "Fund three proof-of-work learning cohorts.", useOfFunds: "Learner bounties, expert reviewers and platform operations.", status: "funded", createdAt: "2026-09-20T10:00:00.000Z" },
  ],
  reactions: { "idea-nightjar:u-maya": "like", "post-aisha-wallets:u-maya": "like" },
  interests: ["idea-nightjar:u-maya", "idea-agentcommons:u-maya"],
  localAccounts: [],
};

export function freshDemoState(): PassionHouseState {
  return JSON.parse(JSON.stringify(demoState)) as PassionHouseState;
}
