import type { PassionHouseState } from "@/lib/passionhouse-types";

export const demoState: PassionHouseState = {
  schemaVersion: 2,
  currentUserId: null,
  users: [
    {
      id: "u-maya",
      name: "Maya Chen",
      handle: "@mayabuilds",
      email: "maya@passionhouse.demo",
      title: "Product founder · circular commerce",
      bio: "I turn overlooked operational problems into products people can adopt without changing how they work.",
      location: "London, UK",
      skills: ["Product strategy", "Marketplaces", "Climate", "Fundraising"],
      avatarTone: "#d8ff57",
      credibility: 92,
      credibilityBreakdown: { external: 96, execution: 91, community: 88, responsiveness: 94 },
      verifications: ["Ethos verified", "LinkedIn", "2 founder references"],
      projectsBuilt: 4,
      collaborations: 18,
      responseRate: 96,
      joinedAt: "2026-03-14T10:00:00.000Z",
      availableFor: ["Co-founders", "Pilot partners", "Product advisory"],
      socials: [
        { platform: "X", handle: "@mayabuilds", url: "https://x.com/mayabuilds", connected: true, followers: 28400, growth30d: 12.4, trustContribution: 18 },
        { platform: "LinkedIn", handle: "maya-chen", url: "https://linkedin.com", connected: true, followers: 8400, growth30d: 4.1, trustContribution: 12 },
        { platform: "GitHub", handle: "mayachen", url: "https://github.com", connected: false, followers: 0, growth30d: 0, trustContribution: 8 },
        { platform: "Website", handle: "mayachen.work", url: "https://example.com", connected: true, trustContribution: 5 },
      ],
    },
    {
      id: "u-idris",
      name: "Idris Bello",
      handle: "@idrisbuilds",
      email: "idris@passionhouse.demo",
      title: "Full-stack engineer · systems builder",
      bio: "Fast product engineering for marketplaces, AI workflows and products with complicated permissions.",
      location: "Berlin, DE",
      skills: ["TypeScript", "AI systems", "Payments", "Architecture"],
      avatarTone: "#89c7ff",
      credibility: 88,
      credibilityBreakdown: { external: 84, execution: 95, community: 86, responsiveness: 89 },
      verifications: ["Ethos verified", "GitHub", "3 builder references"],
      projectsBuilt: 11,
      collaborations: 23,
      responseRate: 91,
      joinedAt: "2026-04-02T10:00:00.000Z",
      availableFor: ["Technical co-founder", "Architecture", "MVP sprints"],
      socials: [
        { platform: "X", handle: "@idrisbuilds", url: "https://x.com/idrisbuilds", connected: true, followers: 17200, growth30d: 8.7, trustContribution: 17 },
        { platform: "GitHub", handle: "idrisbuilds", url: "https://github.com", connected: true, followers: 3200, growth30d: 6.2, trustContribution: 16 },
        { platform: "LinkedIn", handle: "idris-bello", url: "https://linkedin.com", connected: true, followers: 5100, growth30d: 2.8, trustContribution: 9 },
      ],
    },
    {
      id: "u-sofia",
      name: "Sofia Ramirez",
      handle: "@sofiar",
      email: "sofia@passionhouse.demo",
      title: "Growth operator · community products",
      bio: "I validate distribution before scaling the product around it.",
      location: "Mexico City, MX",
      skills: ["Go-to-market", "Research", "Community", "Partnerships"],
      avatarTone: "#ff9f87",
      credibility: 84,
      credibilityBreakdown: { external: 89, execution: 79, community: 94, responsiveness: 82 },
      verifications: ["Ethos verified", "LinkedIn"],
      projectsBuilt: 6,
      collaborations: 31,
      responseRate: 88,
      joinedAt: "2026-02-19T10:00:00.000Z",
      availableFor: ["Go-to-market", "Community design", "Launch partners"],
      socials: [
        { platform: "X", handle: "@sofiar", url: "https://x.com/sofiar", connected: true, followers: 41800, growth30d: 19.6, trustContribution: 20 },
        { platform: "LinkedIn", handle: "sofia-ramirez", url: "https://linkedin.com", connected: true, followers: 12600, growth30d: 7.4, trustContribution: 12 },
        { platform: "Instagram", handle: "@sofia.builds", url: "https://instagram.com", connected: true, followers: 22800, growth30d: 15.1, trustContribution: 10 },
      ],
    },
    {
      id: "u-theo",
      name: "Theo Morgan",
      handle: "@theomakes",
      email: "theo@passionhouse.demo",
      title: "AI product designer",
      bio: "Research-led product design for complex tools that need to feel obvious.",
      location: "New York, US",
      skills: ["Product design", "AI UX", "Prototyping", "Research"],
      avatarTone: "#c6a8ff",
      credibility: 86,
      credibilityBreakdown: { external: 82, execution: 92, community: 83, responsiveness: 87 },
      verifications: ["Ethos verified", "Portfolio", "2 client references"],
      projectsBuilt: 9,
      collaborations: 16,
      responseRate: 93,
      joinedAt: "2026-05-08T10:00:00.000Z",
      availableFor: ["Product design", "Design partnerships", "AI UX"],
      socials: [
        { platform: "X", handle: "@theomakes", url: "https://x.com/theomakes", connected: true, followers: 9800, growth30d: 10.2, trustContribution: 15 },
        { platform: "LinkedIn", handle: "theo-morgan", url: "https://linkedin.com", connected: true, followers: 6800, growth30d: 3.9, trustContribution: 11 },
        { platform: "Website", handle: "theomakes.design", url: "https://example.com", connected: true, trustContribution: 6 },
      ],
    },
    {
      id: "u-amara",
      name: "Amara Okafor",
      handle: "@amaraops",
      email: "amara@passionhouse.demo",
      title: "Health operations founder",
      bio: "Building better infrastructure for the people doing frontline care work.",
      location: "Lagos, NG",
      skills: ["Healthtech", "Operations", "Enterprise sales", "Compliance"],
      avatarTone: "#ffd36e",
      credibility: 90,
      credibilityBreakdown: { external: 94, execution: 88, community: 91, responsiveness: 87 },
      verifications: ["Ethos verified", "LinkedIn", "Domain credential"],
      projectsBuilt: 5,
      collaborations: 14,
      responseRate: 90,
      joinedAt: "2026-01-25T10:00:00.000Z",
      availableFor: ["Health pilots", "Operations", "Enterprise partnerships"],
      socials: [
        { platform: "X", handle: "@amaraops", url: "https://x.com/amaraops", connected: true, followers: 13700, growth30d: 7.8, trustContribution: 16 },
        { platform: "LinkedIn", handle: "amara-okafor", url: "https://linkedin.com", connected: true, followers: 11900, growth30d: 5.3, trustContribution: 14 },
        { platform: "Instagram", handle: "@amara.care", url: "https://instagram.com", connected: false, followers: 3600, growth30d: 2.1, trustContribution: 7 },
      ],
    },
    {
      id: "u-ren",
      name: "Ren Ito",
      handle: "@renlabs",
      email: "ren@passionhouse.demo",
      title: "Fintech engineer · ex-risk systems",
      bio: "I build trustworthy financial products around the edge cases others ignore.",
      location: "Singapore",
      skills: ["Fintech", "Risk", "Backend", "Data"],
      avatarTone: "#78e5d1",
      credibility: 89,
      credibilityBreakdown: { external: 91, execution: 93, community: 78, responsiveness: 92 },
      verifications: ["Ethos verified", "GitHub", "Employment verified"],
      projectsBuilt: 13,
      collaborations: 19,
      responseRate: 95,
      joinedAt: "2026-03-30T10:00:00.000Z",
      availableFor: ["Fintech systems", "Risk review", "Backend engineering"],
      socials: [
        { platform: "X", handle: "@renlabs", url: "https://x.com/renlabs", connected: true, followers: 7600, growth30d: 4.8, trustContribution: 14 },
        { platform: "GitHub", handle: "ren-labs", url: "https://github.com", connected: true, followers: 4100, growth30d: 7.7, trustContribution: 18 },
        { platform: "LinkedIn", handle: "ren-ito", url: "https://linkedin.com", connected: true, followers: 8900, growth30d: 3.2, trustContribution: 12 },
      ],
    },
  ],
  ideas: [
    {
      id: "idea-loopline",
      creatorId: "u-maya",
      title: "Loopline",
      oneLiner: "The returns network small brands can share instead of rebuilding.",
      description: "A shared reverse-logistics layer that lets independent commerce brands pool returns, local inspection and resale. The customer gets one clean experience; brands recover more value without standing up warehouse operations. The wedge is a common condition-grading protocol: one trusted language for deciding what can be restocked, repaired, bundled or routed to local resale. Twelve brands have signed pilot letters, and the first city cluster is dense enough to test whether pooled routes can change the unit economics.",
      category: "Climate",
      stage: "Validated",
      createdAt: "2026-09-22T09:00:00.000Z",
      signal: 94,
      tags: ["Commerce", "Logistics", "Circular economy"],
      asks: ["Full-stack engineer", "Pilot brand introductions"],
      validation: [
        { label: "Interviews", value: "84", detail: "Customers + operators" },
        { label: "Pilot LOIs", value: "12", detail: "Across 4 categories" },
        { label: "Waitlist", value: "462", detail: "+18% this week" },
      ],
      likes: 218,
      dislikes: 9,
      interested: 47,
      commentsCount: 24,
      visibility: "public",
      media: [
        { id: "media-loopline-1", kind: "image", name: "Loopline network map", url: "/media/loopline.svg", visibility: "public" },
        { id: "media-loopline-2", kind: "image", name: "Pilot unit economics", url: "/media/private-blueprint.svg", visibility: "private" },
      ],
      accessTiers: {
        context: "Market map, interview themes and the core operating thesis.",
        build: "Pilot workflow, unit economics ranges and product requirements.",
        full: "Named pilot pipeline, financial model and founder execution plan.",
      },
    },
    {
      id: "idea-nightjar",
      creatorId: "u-theo",
      title: "Nightjar",
      oneLiner: "A private AI workspace for teams that cannot leak the question.",
      description: "A deployable research and drafting copilot for regulated teams, with source-level permissions and a visible decision trail. Designed for legal, compliance and clinical operations.",
      category: "AI",
      stage: "Prototype",
      createdAt: "2026-09-24T12:00:00.000Z",
      signal: 91,
      tags: ["AI", "Privacy", "Enterprise"],
      asks: ["Security engineer", "Compliance design partner"],
      validation: [
        { label: "Design partners", value: "7", detail: "2 paid pilots" },
        { label: "Weekly tests", value: "126", detail: "Across 31 users" },
        { label: "Time saved", value: "6.4h", detail: "Per user / week" },
      ],
      likes: 186,
      dislikes: 6,
      interested: 39,
      commentsCount: 18,
      visibility: "public",
      media: [
        { id: "media-nightjar-1", kind: "image", name: "Private workspace concept", url: "/media/nightjar.svg", visibility: "public" },
        { id: "media-nightjar-2", kind: "image", name: "Security architecture", url: "/media/private-blueprint.svg", visibility: "private" },
      ],
      accessTiers: {
        context: "Problem evidence, category map and target workflows.",
        build: "Architecture decisions, interaction model and pilot learnings.",
        full: "Security design, named pipeline and commercial model.",
      },
    },
    {
      id: "idea-civicsignal",
      creatorId: "u-sofia",
      title: "CivicSignal",
      oneLiner: "Turn neighborhood friction into a prioritized city action queue.",
      description: "Residents submit small local issues through familiar channels. CivicSignal clusters evidence, verifies urgency and gives city teams one actionable operating view.",
      category: "Civic",
      stage: "Early traction",
      createdAt: "2026-09-19T08:30:00.000Z",
      signal: 88,
      tags: ["Govtech", "Community", "Data"],
      asks: ["Civic data engineer", "Municipal advisor"],
      validation: [
        { label: "Reports", value: "1.8k", detail: "In 2 districts" },
        { label: "Resolution", value: "41%", detail: "Up from 17%" },
        { label: "City teams", value: "3", detail: "In evaluation" },
      ],
      likes: 143,
      dislikes: 12,
      interested: 31,
      commentsCount: 29,
      visibility: "public",
      media: [
        { id: "media-civic-1", kind: "image", name: "CivicSignal operations view", url: "/media/civicsignal.svg", visibility: "public" },
      ],
      accessTiers: {
        context: "Research synthesis and stakeholder map.",
        build: "Triage taxonomy, field workflow and data requirements.",
        full: "City contacts, pilot agreement and procurement strategy.",
      },
    },
    {
      id: "idea-atlascare",
      creatorId: "u-amara",
      title: "Atlas Care",
      oneLiner: "Shift handovers that frontline care teams can actually trust.",
      description: "A lightweight handover layer for distributed care teams that converts voice notes and fragmented updates into role-specific, auditable next actions.",
      category: "Health",
      stage: "Pilot",
      createdAt: "2026-09-17T14:15:00.000Z",
      signal: 90,
      tags: ["Healthtech", "Operations", "Workflow"],
      asks: ["Clinical product designer", "Mobile engineer"],
      validation: [
        { label: "Care teams", value: "9", detail: "3 active pilots" },
        { label: "Missed tasks", value: "−32%", detail: "Over 6 weeks" },
        { label: "Shift saves", value: "22m", detail: "Median per handover" },
      ],
      likes: 171,
      dislikes: 4,
      interested: 36,
      commentsCount: 16,
      visibility: "public",
      media: [
        { id: "media-atlas-1", kind: "image", name: "Atlas Care handover", url: "/media/atlascare.svg", visibility: "public" },
      ],
      accessTiers: {
        context: "Workflow research and problem framing.",
        build: "Pilot map, consent model and product requirements.",
        full: "Partner facilities, detailed metrics and rollout plan.",
      },
    },
    {
      id: "idea-kite",
      creatorId: "u-ren",
      title: "Kite Ledger",
      oneLiner: "Cash-flow certainty for businesses paid across borders.",
      description: "A treasury assistant for small global service businesses that predicts settlement gaps, groups obligations and recommends the safest time to convert or move cash.",
      category: "Fintech",
      stage: "Validated",
      createdAt: "2026-09-15T10:45:00.000Z",
      signal: 87,
      tags: ["Fintech", "Treasury", "SMB"],
      asks: ["Fintech counsel", "Growth co-founder"],
      validation: [
        { label: "Linked volume", value: "$1.2m", detail: "Monthly flows" },
        { label: "Beta teams", value: "28", detail: "12 weekly active" },
        { label: "Avoided fees", value: "$31k", detail: "Estimated annual" },
      ],
      likes: 132,
      dislikes: 8,
      interested: 28,
      commentsCount: 12,
      visibility: "public",
      media: [
        { id: "media-kite-1", kind: "image", name: "Kite treasury timeline", url: "/media/kite.svg", visibility: "public" },
      ],
      accessTiers: {
        context: "Customer research and market wedge.",
        build: "Risk logic, data model and beta feedback.",
        full: "Financial model, banking conversations and roadmap.",
      },
    },
    {
      id: "idea-proofstack",
      creatorId: "u-idris",
      title: "Proofstack",
      oneLiner: "A portable evidence layer for independent specialists.",
      description: "A structured work passport that turns outcomes, references and verified contributions into reusable proof—without reducing people to a star rating.",
      category: "Future of work",
      stage: "Concept",
      createdAt: "2026-09-25T17:20:00.000Z",
      signal: 82,
      tags: ["Identity", "Work", "Reputation"],
      asks: ["Trust researcher", "Marketplace operator"],
      validation: [
        { label: "Interviews", value: "43", detail: "Freelancers + buyers" },
        { label: "Prototype tests", value: "19", detail: "74% completion" },
        { label: "Design partners", value: "4", detail: "Talent networks" },
      ],
      likes: 98,
      dislikes: 11,
      interested: 21,
      commentsCount: 9,
      visibility: "public",
      media: [
        { id: "media-proof-1", kind: "image", name: "Portable proof graph", url: "/media/proofstack.svg", visibility: "public" },
      ],
      accessTiers: {
        context: "Trust research and market landscape.",
        build: "Credential format, verification flow and prototype.",
        full: "Partner discussions, technical plan and launch thesis.",
      },
    },
  ],
  comments: [
    { id: "c-1", ideaId: "idea-loopline", userId: "u-idris", body: "The shared inspection layer is the wedge. Have you tested how much brands will standardize condition grading?", createdAt: "2026-09-25T13:20:00.000Z" },
    { id: "c-2", ideaId: "idea-loopline", userId: "u-sofia", body: "The 12 LOIs make this unusually concrete. I can introduce two accessories brands if that pilot segment is useful.", createdAt: "2026-09-25T14:05:00.000Z" },
    { id: "c-3", ideaId: "idea-nightjar", userId: "u-maya", body: "The decision trail feels more defensible than another generic private chat interface.", createdAt: "2026-09-25T16:30:00.000Z" },
  ],
  accessRequests: [
    { id: "req-1", ideaId: "idea-loopline", userId: "u-idris", requestedTier: "full", role: "Technical co-founder", note: "I have built multi-party logistics systems and can own the pilot architecture. I would start with the grading and routing core.", status: "pending", createdAt: "2026-09-26T09:15:00.000Z" },
    { id: "req-2", ideaId: "idea-loopline", userId: "u-sofia", requestedTier: "build", role: "Growth partner", note: "I can pressure-test the wedge and bring a focused group of independent brands into discovery.", status: "pending", createdAt: "2026-09-26T11:40:00.000Z" },
    { id: "req-3", ideaId: "idea-loopline", userId: "u-theo", requestedTier: "context", grantedTier: "context", role: "Product designer", note: "Interested in the returns experience and operator tooling.", status: "approved", createdAt: "2026-09-24T10:00:00.000Z" },
    { id: "req-4", ideaId: "idea-nightjar", userId: "u-maya", requestedTier: "build", grantedTier: "build", role: "Product collaborator", note: "I can help turn pilot learning into a repeatable implementation playbook.", status: "approved", createdAt: "2026-09-23T16:30:00.000Z" },
  ],
  proposals: [
    { id: "prop-1", ideaId: "idea-loopline", fromUserId: "u-idris", toUserId: "u-maya", title: "Pilot architecture sprint", summary: "Turn the current pilot map into a working operator console and brand-facing returns flow.", scope: "Technical architecture, clickable system flow, grading model and a production-ready pilot backlog.", timeline: "4 weeks", budget: "$8,500 fixed", status: "sent", createdAt: "2026-09-26T13:10:00.000Z" },
    { id: "prop-2", ideaId: "idea-nightjar", fromUserId: "u-maya", toUserId: "u-theo", title: "Pilot-to-product operating sprint", summary: "Package the strongest pilot workflows into a repeatable product and onboarding system.", scope: "Workflow prioritization, customer feedback cadence, pilot success scorecard and commercialization plan.", timeline: "6 weeks", budget: "$12,000 fixed", status: "accepted", createdAt: "2026-09-21T15:00:00.000Z" },
  ],
  dealRooms: [
    {
      id: "deal-nightjar",
      ideaId: "idea-nightjar",
      participantIds: ["u-maya", "u-theo"],
      status: "active",
      agreement: {
        title: "Pilot-to-product operating sprint",
        budget: "$12,000",
        timeline: "6 weeks · ends Nov 4",
        ownership: "Nightjar retains all product IP",
        platformEquity: "0% — PassionHouse takes no equity",
      },
      milestones: [
        { id: "m-1", title: "Pilot evidence synthesis", due: "Sep 30", amount: "$2,000", status: "complete" },
        { id: "m-2", title: "Core workflow specification", due: "Oct 12", amount: "$4,000", status: "active" },
        { id: "m-3", title: "Commercial playbook", due: "Nov 4", amount: "$6,000", status: "upcoming" },
      ],
      messages: [
        { id: "dm-1", userId: "u-theo", body: "I added the anonymized pilot notes and marked the three workflows with strongest repeat usage.", createdAt: "2026-09-25T15:12:00.000Z" },
        { id: "dm-2", userId: "u-maya", body: "Perfect. I will turn those into the prioritization scorecard before our review tomorrow.", createdAt: "2026-09-25T15:18:00.000Z" },
      ],
      documents: [
        { id: "doc-1", name: "Signed collaboration terms.pdf", size: "428 KB", uploadedBy: "u-theo" },
        { id: "doc-2", name: "Pilot evidence synthesis.pdf", size: "1.8 MB", uploadedBy: "u-maya" },
        { id: "doc-3", name: "Workflow scoring.xlsx", size: "96 KB", uploadedBy: "u-maya" },
      ],
    },
  ],
  reactions: {
    "idea-nightjar:u-maya": "like",
  },
  interests: ["idea-nightjar:u-maya"],
  localAccounts: [],
};

export function freshDemoState(): PassionHouseState {
  return JSON.parse(JSON.stringify(demoState)) as PassionHouseState;
}
